### ISSUE TITLE
Permit comparison of complete objects

### ISSUE THREAD

**Issue by yovasx2** [brooklynDev/airborne#106]
Instead of test element by element value. You can be able to compare the complete object:
Suppose you have next JSON

    {"data":` "restaurant": { "id": 1, "name": "Number 1", ... } }

An an object restaurant typre Restaurant, so istead of doing:

    expect_json('data.restaurant', id: restaurant.id )
    expect_json('data.restaurant', name: restaurant.name )
    ...

You have the possibility to do:

    expect_json('data', restaurant: restaurant )

**Comment by sethpollack** [comment]
This is not something that we plan to support right now. You can always just convert your object to a hash.

**Comment by sethpollack** [comment]
Also you don't need a separate test for each property:

```ruby
expect_json('data.restaurant', id: restaurant.id, name: restaurant.name )
```
