### ISSUE TITLE
How to set verify_ssl  => false

### ISSUE THREAD

**Issue by kagalenitin** [brooklynDev/airborne#118]
I want to bypass ssl by setting it to false. In RestClient, I can set by passing verify_ssl: false, but I didn't find anything in Airborne. Am I missing something? I looked up the issues and didn't find anywhere, also searched for SSL in the code base, but nothing in there.

I used: OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE unless OpenSSL::SSL::VERIFY_PEER==0 but I get a warning

WARNING: OpenSSL::SSL::VERIFY_PEER == OpenSSL::SSL::VERIFY_NONE
This dangerous monkey patch leaves you open to MITM attacks!
Try passing :verify_ssl => false instead. 

Has anyone run into this before? Any help would be appreciated.

**Comment by torandu** [comment]
@brooklynDev Is there a recommended solution or workaround? I have the same need to run tests with :verify_ssl => false. Thanks!

**Comment by con91** [comment]
yeah Im in the same situation, cant seem to pass  :verify_ssl => false with airborne

**Comment by abdulgmohd** [comment]
@brooklynDev,  Any update or workaround for this issue?

Thanks.

**Comment by mycargus** [comment]
@sethpollack I'm being a bit selfish here but this one is has become important to me and my team. I'll see if I can put together a PR for it. Hopefully it's as simple as passing the hash down to RestClient.
