### ISSUE TITLE
Use of stabby lambda's is breaking jRuby support

### ISSUE THREAD

**Issue by chrsgrrtt** [brooklynDev/airborne#21]
There is a syntax error when using jRuby resulting from the use of stabby lamdba's. Tested with jruby 1.7.16 in 1.9 mode, so likely to exist on earlier versions.

One example can be found in [request_expectations.rb](https://github.com/brooklynDev/airborne/blob/master/lib/airborne/request_expectations.rb#L214) where 
`-> (data) { expect(data.size).to eq(expected_size) }` 
could be replaced with 
`->(data) { expect(data.size).to eq(expected_size) }` 
to avoid syntax errors (note the removal of the space after the dash rocket).

**Comment by namxam** [comment]
Unfortunately, the error is back with the latest version:
```ruby
SyntaxError: /Users/maximilianschulz/.rvm/gems/jruby-1.7.20/gems/airborne-0.1.16/lib/airborne/request_expectations.rb:56: syntax error, unexpected tLPAREN_ARG
      -> (value) { yield DateTime.parse(value) }
```
