### ISSUE TITLE
undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by fmorales** [brooklynDev/airborne#31]
When I hit this uri
http://voteapi-cloud-test.telescope.tv/moderation/getMessages?topic_id=1000336

and use this expectation
  expect_json_keys('0', [:position])

I get this error:

 1) Test Endpoint  - has the correct keys
     Failure/Error: expect_json_keys('0', [:position])
     NoMethodError:
       undefined method `keys' for nil:NilClass
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:23:in `block in expect_json_keys'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:87:in `block in call_with_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/path_matcher.rb:24:in `get_by_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:86:in `call_with_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:22:in `expect_json_keys'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:61:in `call'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.8/lib/airborne/request_expectations.rb:61:in `block (2 levels) in <module:RequestExpectations>'
     # ./spec/sandbox/toys_rspec.rb:23:in `block (2 levels) in <top (required)>'

As far as I can tell I am calling expect_json_keys exactly like the documentation specifies. What is going wrong?

**Comment by sethpollack** [comment]
Thanks for pointing out the bug, I just pushed a fix.

**Comment by fmorales** [comment]
Thank you so much. I was pulling my hair out.

**Comment by sethpollack** [comment]
No Problem.

**Comment by IanVaughan** [comment]
Is this still an issue for anyone?
I have `match_actual: true`, and get the error on a basic assertion `expect_json("0", errors: {})

I get it with either versions : 0.2.3, 0.2.6.

response: 
```
=> [{"key"=>"value",
  "id"=>"20160811-0a4ebf34",
...
 ```

**Comment by IanVaughan** [comment]
Ir raises on `keys << actual.keys if match_actual?`, on the second time in from the `each` block lower down.
Its because `extract_actual` returns `nil` as the key in the nested hash, which is not present!

```
> expected #=> {:errors=>{}}
> expected_value #=> {}
> actual #=> {:transport_mode=>"scooter"... (no "errors" key!)
> actual_value #=> nil
```

**Comment by IanVaughan** [comment]
@sethpollack is this something you can comment on?
Should I raise a new issue?
I will try and write up a failing spec at some point, but would love to hear your thoughts on this.

**Comment by sethpollack** [comment]
Ok I pushed a fix, let me know if it works for you?
