### ISSUE TITLE
Expected ? to be array got Hash from JSON response

### ISSUE THREAD

**Issue by fmorales** [brooklynDev/airborne#33]
When I hit this uri
http://voteapi-cloud-test.telescope.tv/moderation/getMessages?topic_id=1000336

and use this expectation
expect_json_keys('?', [:position])

I get this error:

 1) Test Endpoint  - has the correct keys
     Failure/Error: expect_json_keys('?', [:position])
       Expected ? to be array got Hash from JSON response
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/path_matcher.rb:99:in `ensure_array'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/path_matcher.rb:11:in `block in get_by_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/path_matcher.rb:9:in `each'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/path_matcher.rb:9:in `each_with_index'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/path_matcher.rb:9:in `get_by_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/request_expectations.rb:87:in `call_with_path'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/request_expectations.rb:23:in `expect_json_keys'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/request_expectations.rb:62:in `call'
     # /Users/francesmorales/.rvm/gems/ruby-2.1.2/gems/airborne-0.1.10/lib/airborne/request_expectations.rb:62:in `block (2 levels) in <module:RequestExpectations>'
     # ./spec/sandbox/toys_rspec.rb:22:in `block (2 levels) in <top (required)>'

I get the same error for *

Am I still running into a bug, or am I doing something wrong?

**Comment by sethpollack** [comment]
Yes, the `?` and `*` are for checking against elements in an array. Your api is returning a hash. What are you trying to test for?

**Comment by fmorales** [comment]
I am trying to check that all the nodes returned contain :position, instead of just 0. How do I do that?

**Comment by sethpollack** [comment]
Offhand, you can loop through the keys on `json_body` and call `expect_json_keys` for each.

Some thing like this:
```ruby
json_body.keys.each do |el|
  expect_json_keys(el, [:position])
end
```

**Comment by brooklynDev** [comment]
An alternative approach to what @sethpollack posted, is to use a little bit of hackery:

```ruby
    @json_body = json_body.values
    expect_json_keys('?', [:position])
```

This relies on some implementation details of `airborne` but will work as well. The main issue is that you're treating an object like that of an array. If we see more use cases for this in the future, we can add support to `airborne` for this.

**Comment by fmorales** [comment]
Alex, 
	Thank you. That’s hacky, but it does in fact do what I need it to do. Thanks for much for pointing out how to do that.
-Frances
