### ISSUE TITLE
Loading multiple grape apps

### ISSUE THREAD

**Issue by adamgotterer** [brooklynDev/airborne#35]
I'm mounting multiple grape endpoints into rails. I'm able to use `config.rack_app` to set the app in each spec file without issue. But I was wondering if I could mass load (maybe in rspec) all the endpoints so they are all routable and available at once? Thanks!

**Comment by brooklynDev** [comment]
Since Rails itself is rack based, `airborne` supports Rails. Have you tried mounting the Rails application itself?

**Comment by adamgotterer** [comment]
That worked for me. Thanks!
