### ISSUE TITLE
upgrade rest-client dependency

### ISSUE THREAD

**Issue by drewda** [brooklynDev/airborne#41]
FYI, `rest-client` has a security vulnerability in the versions required by `airborne`: http://www.osvdb.org/show/osvdb/117461

It's fixed in 1.7.3: https://github.com/rest-client/rest-client/blob/master/history.md#173

**Comment by sethpollack** [comment]
Thanks so much. Here is the commit: https://github.com/brooklynDev/airborne/commit/1b30fbb82036586b17da58bfbfaa330869ae3c8e

**Comment by drewda** [comment]
Great, thanks for such a quick update.
