### ISSUE TITLE
No params = {} parameter in GET request?

### ISSUE THREAD

**Issue by zisismaras** [brooklynDev/airborne#45]
After some failures i noticed that you don't use params = {} parameter in the GET request as rack-test does.So you have to interpolate it like:  
```ruby
get "/endpoint?foo=#{test}"
```
But in ruby < 2.2 it gives a bad URI error so i had to use URI.encode  

Why is that?  
Thanks!

**Comment by dan-klasson** [comment]
Maybe I don't understand you, but you can do:

    get '/users/123',  'params' => {'foo' => 'bar'}

**Comment by zisismaras** [comment]
I must have been doing something wrong, it works as expected, please close this.

Thanks
