### ISSUE TITLE
How to provide forms parameters for POST?

### ISSUE THREAD

**Issue by neilyoung** [brooklynDev/airborne#46]

**Comment by Rodney-QAGeek** [comment]
Hi Niel,

I figured out how to Post with parameters using a 'params' header. See below:
```Ruby
post '/my_url', {'params' => {my_param1: 123, my_param2: 'abc'}}
```

I've discovered this by looking at the source code for [RestClient](https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb). Specifically line 213 of request.rb 

Maybe we should update the airborne Readme with a params example.

**Comment by neilyoung** [comment]
Ah, thanks for letting me know.

Regards

**Comment by Rodney-QAGeek** [comment]
No Problem! @brooklynDev I've added a [pull request](https://github.com/brooklynDev/airborne/pull/49) for the Readme.

**Comment by brooklynDev** [comment]
@Rodney-QAGeek Thanks, looks good! I've merged it in.

**Comment by neilyoung** [comment]
BTW: It is already a couple of days ago. I reviewed my sources and found this solution (which works as well):

    post 'token', 
      "username=#{CGI::escape(user[:username])}&password=#{CGI::escape(user[:password])}&grant_type=password&client_id=#{CGI::escape(CLIENT_ID)}",
      {:content_type => 'application/x-www-form-urlencoded', :accept => 'application/json'}
