### ISSUE TITLE
Can `subject` be called when one of the API methods is called? 

### ISSUE THREAD

**Issue by PikachuEXE** [brooklynDev/airborne#47]
I have many context group for my controller spec.
But I always needs to add the `get /path` at the very end BUT in before hook

I just tried put the `get` in `subject` to avoid the repeated call, it works with [`json_spec`](https://github.com/collectiveidea/json_spec) since they implement with custom matcher.
But it doesn't work with this gem, with error complaining about missing `json_body`, meaning `subject` is not called.

Is there a way to make it call `subject` when one of the API methods (e.g. `expect_json_types`) is called?

**Comment by sethpollack** [comment]
@PikachuEXE do you have an example of what you are trying to do?

**Comment by PikachuEXE** [comment]
```ruby
subject do
  call_action
  controller
end

let(:call_action) do
  get :index
end

it {expect_json_types(pagination: :object)}
it {expect_json_types("data", {posts: :array_of_objects})}
it {expect_json_sizes("data", {listings: 1})}
```

**Comment by drewcimino** [comment]
I think using `subject { call_action; controller }` is abusing the subject block a little bit.

subject isn't a substitute for `before`, it's shorthand for:
```
let(:thing)
...
  expect(thing).to be_something
...
```

In many cases, when you're using the shorthand test syntax `it { is_expected.to be_something }`, the code in your subject is _in effect_ run like it is in a before block, but it's not guaranteed (nor should it be).

**Comment by sethpollack** [comment]
I agree. I don't think that is what `subject` is meant for.

**Comment by PikachuEXE** [comment]
Regardless of how I use / abuse `subject`, the question I am asking here is: is it intended to not call `subject`?

**Comment by sethpollack** [comment]
Its not that we are intentionally not calling the `subject` hook, we just had no reason to do so. 

Normally RSpec expectation take both the `subject` and the `expectation`, however with Airborne, we just use the response as the `subject` and therefore have no reason to be calling the `subject` hook.

Is there a use-case other than the one above where it would make sense to do so?

**Comment by PikachuEXE** [comment]
I will find my own way to solve this then.
Thanks for your time.

**Comment by sethpollack** [comment]
No problem. You can wrapping the methods in your `spec_helper`

```ruby
    [:expect_json_types, :expect_json, :expect_json_keys, :expect_status, :expect_header, :expect_header_contains].each do |method_name|
      method = instance_method(method_name)
      define_method(method_name) do |*args, &block|
        subject()
        method.bind(self).call(*args, &block)
      end
    end
```

**Comment by PikachuEXE** [comment]
I am already do the same thing (with another way).
Thanks anyway.

**Comment by sethpollack** [comment]
Ok no problem!
