### ISSUE TITLE
Error on http://brooklyndev.github.io/airborne/

### ISSUE THREAD

**Issue by tit** [brooklynDev/airborne#54]
http://brooklyndev.github.io/airborne/ (in bottom) have some code snippet:
```
Airborne.configure.do |config|
  config.base_url = 'http://example.com/api/v1'
  config.headers = {'x-auth-token' => 'my_token'}
end
```
Not work.

`Airborne.configure.do |config|` => `Airborne.configure do |config|`

**Comment by sethpollack** [comment]
Thanks, I will update!
