### ISSUE TITLE
head :no_content issue

### ISSUE THREAD

**Issue by victorhazbun87** [brooklynDev/airborne#57]
This is my test:

      it "returns expected json" do
        delete :destroy, id: @location_1.id
        expect_json(nil)
      end
This is my code destroy action:

        def destroy
          location = Location.find(params[:id])
          authorize! :crud, Location
          location.destroy
          head :no_content
        end

This is the rspec output:

        Failure/Error: expect_json(nil)
        Airborne::InvalidJsonError:
        Api request returned invalid json

When I inspect the response body:

        response.body #=> ""

Please tell me how I should test this scenario give my code ---> head :no_content

Thank you!

**Comment by brooklynDev** [comment]
I think this might be a case where it's just better to default to regular rspec `expect`. I don't think we need to add anything to `airborne` for this. So in your case it would be something like:

```ruby
  it "returns expected json" do
    delete :destroy, id: @location_1.id
    expect(body).to eq('')
  end
```
