### ISSUE TITLE
better error messages when passing bad options to expect_json_types

### ISSUE THREAD

**Issue by sethpollack** [brooklynDev/airborne#59]
For Example 

```ruby
  it 'should throw a normal error' do 
    get '/foo'
    expect_json_types(foo: :foo )
  end
```

Will throw 

```
NoMethodError:
       undefined method `include?' for nil:NilClass
```

**Comment by brooklynDev** [comment]
+1

Definitely, this has always been something that's bugged us from day one. Maybe I'll finally get around to it this weekend, but I'm willing to accept a PR from anyone (wink wink...)
