### ISSUE TITLE
Add :null to the json_types mapper

### ISSUE THREAD

**Issue by sethpollack** [brooklynDev/airborne#61]
There are scenarios where you may want to make sure that the value is nil.

**Comment by sethpollack** [comment]
This may fall under the `expect_json` responsibility, dunno.

**Comment by brooklynDev** [comment]
+1

I think putting it as part of the type mappers makes sense. The other option would be to have some kind of `undefined(value)` method similar to how we have `optional` but I kinda like your suggestions better.

**Comment by sethpollack** [comment]
Ok ill work on this.
