### ISSUE TITLE
Changelog and semantic versioning

### ISSUE THREAD

**Issue by theodorton** [brooklynDev/airborne#63]
I understand that this gem is unstable until a v1.x is release, but the latest v0.1.16 introduced some breaking changes (`expect_json` is more strict in how it diffs actual and expected responses).

It would be great if this gem would adapt [Semantic Versioning](http://semver.io/) and start [keeping a changelog](http://keepachangelog.com/).

I could submit i PR with a changelog for the current versions, but it works best when there are tags for each of the released versions.

**Comment by sethpollack** [comment]
Ok I added the tags.
