### ISSUE TITLE
Why no exact match matcher, what am I overlooking?

### ISSUE THREAD

**Issue by kswope** [brooklynDev/airborne#65]
I'm a little baffled why there's no exact matcher.

In other words, if my api returns

```
{"public":"here","secret":"here"}
```

This happily matches (only matches part, I like it)

```
expect_json(public:'here')                                                                                                                  
```

But I'd expect something like this to exist

```
expect_json_exact(public:'here')                                                                                                                  

```

Maybe its not a secret, maybe its unnecessary data and you are trying to reduce bandwidth used.

**Comment by kennycason** [comment]
:+1: I would like to have both options. (Minor disagreement on naming)
e.g.
```ruby
# only match specific values, don't care about other values.
expect_json({public: 'here'})  
# match every key and every value, strictly. 
expect_json_exact({public: 'here', secret: 'there'})   
```

**Comment by kswope** [comment]
```
expect_only_json( public: 'here' )  
expect_only_json( {public: 'here'}, ignore: ['date', 'time'] )  

```

**Comment by kennycason** [comment]
I think that's just as verbose as you end up having to specify what you ignore, which could be a lot depending on the test. I think i'd rather just have two methods. One that matches all values, exactly, and one that acts as a whitelist and only matches/verifies the specified fields. 

I know that having expect_json now validate ALL fields like it does in version 16 was enough to prevent me from upgrading as we have a lot of tests that are testing very specific fields during testing large responses.

**Comment by kswope** [comment]
I didn't know a previous version already did what I'm asking for, I'm sorry to hear that.  I think I'll just try combining airborne with https://github.com/collectiveidea/json_spec since it seems to have a better thought out functionality.  Not sure if they'll play nicely together yet.

**Comment by kennycason** [comment]
Thanks for the reference! I'll check it out as well :)

**Comment by sethpollack** [comment]
The plan is to add options which can be configured in the `Airborne.configure` block or passed into individual tests.

The options will allow you to test:
1. That all keys in the expected hash are in the response.
2. That all keys in the response are in the expected hash.

So if you only want to check the keys that are in both, you can turn both these options off.
