### ISSUE TITLE
Compatibility with rspec-rails

### ISSUE THREAD

**Issue by colorfulfool** [brooklynDev/airborne#70]
Hi.

I am relatively new to Rails and probably doing something very stupid, but: 
I use Rails with rspec, my tests have `type: :request`. When I call `get`, `post`, etc. in tests, what is actually called is `ActionDispatch::Integration::Runner#get`, not airbornes's `get`. Which leads to some unexpected results, like "Accept" being "text/html" by default and `format:` arg not working. What am I doing wrong?

**Comment by sethpollack** [comment]
You can add `format: :json` to your requests.

**Comment by sethpollack** [comment]
I use it for request specs all the time with no issues. I use `config.infer_spec_type_from_file_location!` rather than `type: :request` but i don't think that should make a difference.

**Comment by colorfulfool** [comment]
`format: json` does work when passed in params hash, but I found another workaround:

    describe 'API for regular users' do
      def reset!
        super
        @integration_session.accept = 'application/json'
      end

**Comment by sethpollack** [comment]
ok awesome!
