### ISSUE TITLE
In case of multiple requests, expect_json keeps checking with response of first request.

### ISSUE THREAD

**Issue by rvsingh** [brooklynDev/airborne#71]
I am making three requests in a rspec example. The responses are correct but the matchers after second request are failing because they keep comparing using the response of first request.   

    describe "Sign Out" do
      it "should expire the auth token" do
        # Sign In
        post "/api/v1/sign_in", {"email": @user.email, "password": @user.password}, :format => :json
        expect_status(200) #OK

        auth_token = response.header['X-Auth-Token']
        email = response.header['X-User-Email']
        
        # Sign out
        post "/api/v1/sign_out", {}, {'X-User-Email' => email, 'X-Auth-Token' => auth_token, 'Content-Type' =>'application/json'}
        body = response.body
        expect_status(200) #OK
        expect_json("message": "Signed out successfully.")

        # Trying with expired token
        get "/api/v1/cycle_days", {'X-User-Email' => email, 'X-Auth-Token' => auth_token}, :format => :json
        expect_status(401)
      end
    end

Here is the error.

       Failure/Error: expect_json("message": "Signed out successfully.")
       
       expected: "Signed out successfully."
            got: "Signed in successfully."

**Comment by sethpollack** [comment]
Yeah, sorry about that. Just pushed a new release with the fix. Thanks!

**Comment by rvsingh** [comment]
Hey, thank you. I think the multiple part is working fine. But now expect_header is failing in all specs

		   Failure/Error: expect_header('X-Auth-Token', @user.authentication_token)
		     NoMethodError:
		       undefined method `[]' for nil:NilClass
		     # /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/airborne-0.1.17/lib/airborne/request_expectations.rb:62:in `expect_header_impl'
		     # /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/airborne-0.1.17/lib/airborne/request_expectations.rb:40:in `expect_header'
		     # ./spec/api/v1/authentication_spec.rb:18:in `block (3 levels) in <top (required)>'

**Comment by sethpollack** [comment]
Ok it should work now, I pushed a new release.

**Comment by rvsingh** [comment]
Thanks a ton for your quick response. But sadly, I think, we are still hitting bump.

	     Failure/Error: expect_header('X-Auth-Token', @user.authentication_token)
	     NoMethodError:
	       undefined method `[]' for nil:NilClass
	     # /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/airborne-0.1.18/lib/airborne/request_expectations.rb:62:in `expect_header_impl'
	     # /Users/rajveershekhawat/.rvm/gems/ruby-2.2.0@rails420/gems/airborne-0.1.18/lib/airborne/request_expectations.rb:40:in `expect_header'
	     # ./spec/api/v1/authentication_spec.rb:19:in `block (3 levels) in <top (required)>'

**Comment by sethpollack** [comment]
Are you using rails?

**Comment by rvsingh** [comment]
Yes

**Comment by sethpollack** [comment]
Ok give me a few.

**Comment by rvsingh** [comment]
Thanks man. Take your time, I owe you a :beer:

**Comment by sethpollack** [comment]
Ok hopefully this time it works!

**Comment by rvsingh** [comment]
Yes, it does. Thank You.

**Comment by sethpollack** [comment]
:+1:

**Comment by vipin8169** [comment]
Does this issue still exist??
I am firing two consecutive requests. first one should pass with 200 and second one should fail with 401. 
I am trying to get the response of the second one, but i am getting the response of first one instead.

**Comment by sethpollack** [comment]
Yes, this was fixed.
