### ISSUE TITLE
Bring gem's interface closer to "idiomatic Ruby"

### ISSUE THREAD

**Issue by colorfulfool** [brooklynDev/airborne#74]
Hi. Have you guys thought about making the calls more "rspec-style"? At least for typical cases (you know, those 20% that are used 80% of the time).

Like, turn 

``` ruby
expect_json '?.category', {name: chosen_category.name}
```

into

``` ruby
expect(:any).to_have :category, with: {name: chosen_category.name}
```

I would love to participate in that.

**Comment by sethpollack** [comment]
There is a plan to add rspec style matchers in addition to the current api. I just need to find the time to work on it.

**Comment by ivan-kolmychek** [comment]
I would like to see that to, but, I think, it's better to use existing convention:
```
expect(response).to have_json(...)
```

We can use chainable matchers to get something like in @colorfulfool example:
```
expect(response).to have_json(name: chosen_category.name).in(:category)
```

What do you think about that?
