### ISSUE TITLE
Clear database before specific test

### ISSUE THREAD

**Issue by CQBinh** [brooklynDev/airborne#75]
I want to test one method when `database` is empty, so i want to `clear` the `database` before my test (only **ONE** test case).
I know that [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner) can clear database *each* test case. But how about **only ONE**?

**Comment by ivan-kolmychek** [comment]
If I understand correctly, its just an RSpec, so, you can call the database cleaning in your example 
```
it 'does something with clean database' do
  DatabaseCleaner.clean
  # rest of your example here
end
```

or put it into `:before` block for that one test. If you want, you can isolate it with context:

```
describe 'Something' do
  context 'with clean database' do
    before { DatabaseCleaner.clean }
    it "does something with clean database" do
      # your example here
    end
  end
end
```
