### ISSUE TITLE
Upload file using post 

### ISSUE THREAD

**Issue by subathra-selvaraj** [brooklynDev/airborne#84]
How to upload a file using airborne

**Comment by subathra-selvaraj** [comment]
BOUNDARY = "AaB03x"
post_body = []
    post_body << "--#{BOUNDARY}\r\n"
    post_body << "Content-Disposition: form-data; name=\"file\"; filename=\"jesus.jpg\"\r\n"
    #post_body << "Content-Type: #{MIME::Types.type_for(file)}\r\n\r\n"
    post_body << "\r\n"
    post_body << File.read(file)
    post_body << "\r\n--#{BOUNDARY}--\r\n"

   post url,post_body.join

**Comment by kanekotic** [comment]
can you explain a bit the solution please?

**Comment by CoplexReviews** [comment]
@subathra-selvaraj @kanekotic a bit late but here is the solution I came up with (relies on RestClient, which is a dependency of airborne). 

You can write out your params as normal with a hash:

```
params = {
              other_param: 'Some param',
              file: File.new(Rails.root.join('spec', 'fixtures', 'sample.csv'), 'r')
          }
      }

multipart = RestClient::Payload::Multipart.new(params)
post endpoint, params: multipart.read, headers: multipart.headers
```

@sethpollack Do you think this would be useful in the README, I'm not sure if it's outside the scope of what you were trying to do but I could imagine several others will run into the same issue.

**Comment by templeman15** [comment]
@subathra-selvaraj @kanekotic a bit late but here is the solution I came up with (relies on RestClient, which is a dependency of airborne).

```
You can write out your params as normal with a hash:	params = {
              other_param: 'Some param',
              file: File.new(Rails.root.join('spec', 'fixtures', 'sample.csv'), 'r')
          }
      }

multipart = RestClient::Payload::Multipart.new(params)
post endpoint, params: multipart.read, headers: multipart.headers	
```

@sethpollack Do you think this would be useful in the README, I'm not sure if it's outside the scope of what you were trying to do but I could imagine several others will run into the same issue.
